global:
  scrape_interval:     1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'example'

rule_files:
   - alert_rules.yml
  # - "second_rules.yml"

alerting:
  alertmanagers:
  - static_configs:
    - targets: ['alertmanager:9093']

scrape_configs:
#  - job_name: 'prometheus'
 #   static_configs:
  #    - targets: ['localhost:9090']

  - job_name: 'node'
    static_configs:
      - targets: ['192.168.123.212:9100']

  - job_name: 'node_secure_graf'
    scheme: https
    static_configs:
      - targets: ['deco-graf.com:9123']
        labels:
          job: "node_secure"
    tls_config:
      ca_file: /certificates/prometheus.pem
      insecure_skip_verify: true

  - job_name: 'node_secure_prom'
    scheme: https
    static_configs:
      - targets: ['deco-prom.com:9123']
        labels:
          job: "node_secure"
    tls_config:
      ca_file: /certificates/prometheus.pem
      insecure_skip_verify: true


  - job_name: 'wmi'
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['192.168.123.1:443']

  - job_name: 'wmi_secure'
    scheme: https
    scrape_interval: 30s
    scrape_timeout: 30s
    static_configs:
      - targets: ['deco-win1.com:9123']
    tls_config:
      ca_file: /certificates/prometheus.pem
      insecure_skip_verify: true

